### ISSUE TITLE
[Feature] [태그] 태그 저장 기능

### ISSUE THREAD

**Issue by ChoMyeongHwan** [sixes-sense/back-end#35]
✏️Description
-
태그 저장 기능 구현

✅TODO
-
- [x] 태그 엔티티 생성
- [x] 태그 저장 기능 구현
- [x] 태그 통합 테스트 진행

🐾ETC
-

**Comment by BearCrying** [comment]
<img width="183" alt="image" src="https://github.com/sixes-sense/back-end/assets/114653516/1aaea73e-c1a4-4624-a63c-98f265bc068b">
요기서 Development에 해당 브렌치 추가할수있어요! 참고하시면 좋을것같습니다
지금은 제가 해놨습니다 확인해주세용~

**Comment by ChoMyeongHwan** [comment]
넵 확인했습니다.
